"""
Perceptual QA: a video-native model watches the generated walkthrough and judges whether it
holds together as a real space in motion.

WHY THIS EXISTS SEPARATELY FROM depth_metrics.py
------------------------------------------------
The numeric check compares geometry frame by frame. It is blind to two things that matter:
a uniformly mis-scaled room (every relative distance preserved, so rank correlation stays
high), and motion artefacts that are not geometric at all -- texture swimming, materials
popping between frames, parallax that feels dreamlike. Those need something that actually
watches the clip, which is what Gemini's native video input provides.

Runs against the Gemini API directly rather than through a ComfyUI node, for cost and
simplicity: it bills the caller's own (cheaper) Gemini quota instead of Comfy's marked-up
partner-API pricing, returns the verdict as a dict with no file round-trip, and supports
response_schema so the JSON is enforced rather than requested politely in the prompt.

Correction to an earlier claim in this file: getting text OUT of a Comfy graph is not
impossible. PreviewAny does render to the UI only and yields no retrievable asset, but
SaveText writes a real .txt that get_output returns and that can be fetched over HTTP --
verified end to end. The reasons above are about cost and ergonomics, not capability.

The response is schema-constrained JSON, not prose, because the retry loop in qa_runner.py
branches on `implicated_dial`. Free-text would have to be regexed, which is exactly the
kind of brittleness this is meant to avoid.
"""
import os
import json
import time
from typing import Dict, Any, Optional

# gemini-2.5-pro returns 429 with `limit: 0` on a free-tier key -- it is paid-only, so it
# is not a usable default here. 2.5-flash is the default because in side-by-side testing it
# was the more critical judge: it caught texture swimming that 3.1-flash-lite scored as a
# clean PASS. For QA, prefer the judge that produces fewer false passes.
#
# UPDATE, Aug 2026: gemini-2.5-flash now returns 404 "no longer available to new users" on this
# key, even though it is still listed by the models endpoint. A listing is not an entitlement --
# check by calling, not by reading the catalogue. gemini-3.6-flash is the current equivalent.
DEFAULT_MODEL = "gemini-3.6-flash"

# Which knob a given symptom implicates, per the failure table in the architectural
# visualization design spec (section 9). The judge picks one; qa_runner turns it into a
# concrete parameter change.
#
# `increase_steps` is not in the spec's table but is needed in practice: the validated run
# sampled at 6 steps, and the spec's own economics section treats 4-step runs as drafts and
# 20-step as finals. Texture swimming on a draft is the expected artefact and more steps is
# the actual fix -- without this option a judge is forced to mis-attribute it to
# control_strength, which binds geometry and would do nothing for surface stability.
DIAL_VALUES = ["none", "control_strength", "add_canny", "denoise_up", "denoise_down",
               "increase_steps"]

VERDICT_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {"type": "string", "enum": ["PASS", "MARGINAL", "FAIL"]},
        "doorway_tracking": {
            "type": "object",
            "properties": {"ok": {"type": "boolean"}, "note": {"type": "string"}},
            "required": ["ok", "note"],
        },
        "wall_stability": {
            "type": "object",
            "properties": {"ok": {"type": "boolean"}, "note": {"type": "string"}},
            "required": ["ok", "note"],
        },
        "flicker": {
            "type": "object",
            "properties": {"ok": {"type": "boolean"}, "note": {"type": "string"}},
            "required": ["ok", "note"],
        },
        "parallax_coherence": {
            "type": "object",
            "properties": {"ok": {"type": "boolean"}, "note": {"type": "string"}},
            "required": ["ok", "note"],
        },
        "implicated_dial": {"type": "string", "enum": DIAL_VALUES},
        "confidence": {"type": "number"},
        "summary": {"type": "string"},
    },
    "required": ["verdict", "doorway_tracking", "wall_stability", "flicker",
                 "parallax_coherence", "implicated_dial", "confidence", "summary"],
}

SIDE_BY_SIDE_PROMPT = """\
You are a QA inspector for an architectural visualization pipeline. Judge geometric
fidelity and temporal stability only -- ignore aesthetic taste.

This video is a side-by-side comparison, exactly time-synchronised frame for frame.

LEFT HALF: a ground-truth depth map rendered directly from real CAD floor-plan geometry.
Brighter = closer to camera. Solid black = void; nothing was modelled beyond the room's
walls, so the area past the doorway is empty by construction, not an error.

RIGHT HALF: a photorealistic video generated by a diffusion model that was given the LEFT
half as its geometric control signal, plus a text prompt for materials and lighting.

The camera performs a forward dolly toward a doorway.

Assess:
1. DOORWAY TRACKING -- does the opening in the RIGHT half hold the same screen position
   and grow at the same rate as the black void in the LEFT half? Cite frame ranges where
   they diverge.
2. WALL STABILITY -- do wall surfaces, corners, and the wall/floor and wall/ceiling
   junction lines stay straight and stable, or wobble, breathe, warp, or drift?
3. FLICKER -- any frame-to-frame flicker, popping, or texture swimming?
4. PARALLAX COHERENCE -- does this read as a real camera moving through a rigid space, or
   dreamlike/morphing?

Then set `implicated_dial` to the single most useful corrective action:
- "none"             -- nothing to fix
- "control_strength" -- walls drift/breathe or geometry does not track: bind the control
                        signal harder
- "add_canny"        -- straight lines wobble and corners read soft, but volume is right:
                        needs an edge signal alongside depth
- "denoise_up"       -- geometry is right but it looks like a CG render, not a photograph
- "denoise_down"     -- looks photoreal but is not obeying the control geometry
- "increase_steps"   -- geometry is stable but SURFACES are unstable: texture swimming,
                        materials shimmering or popping frame to frame. This is the
                        signature of an under-sampled draft, and raising control strength
                        will NOT fix it -- that binds geometry, not texture.

Be critical and specific. `confidence` is 0.0-1.0 in your own verdict.
"""

SINGLE_VIDEO_PROMPT = """\
You are a QA inspector for an architectural visualization pipeline. Judge geometric
plausibility and temporal stability only -- ignore aesthetic taste.

This is a generated photorealistic walkthrough of an apartment interior. The camera
performs a forward dolly toward a doorway. No reference is provided; judge whether it
holds together as a physically real, rigid space.

Assess: (1) doorway tracking as the camera approaches, (2) wall/corner/junction-line
stability, (3) frame-to-frame flicker or texture swimming, (4) whether parallax reads as a
real camera in a rigid space.

Then set `implicated_dial` as instructed by the schema enum, and give a 0.0-1.0
`confidence`.
"""


class GeminiJudge:
    """Video-native perceptual QA. Degrades to a skip (not a crash) without an API key."""

    def __init__(self, api_key: Optional[str] = None, model: str = DEFAULT_MODEL):
        self.model = model
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        if self.api_key:
            from google import genai
            self.client = genai.Client(api_key=self.api_key)
        else:
            self.client = None
            print("WARNING: GEMINI_API_KEY not found. Perceptual QA will be skipped.")

    def _upload(self, video_path: str, timeout_s: int = 180):
        """Files API upload + wait until ACTIVE. Used rather than inline base64 so this
        keeps working for longer clips, where inline would breach the request size cap."""
        uploaded = self.client.files.upload(file=video_path)
        deadline = time.time() + timeout_s
        while uploaded.state.name == "PROCESSING" and time.time() < deadline:
            time.sleep(2)
            uploaded = self.client.files.get(name=uploaded.name)
        if uploaded.state.name != "ACTIVE":
            raise RuntimeError(
                f"Gemini file upload ended in state {uploaded.state.name} for {video_path}")
        return uploaded

    def judge(self, video_path: str, side_by_side: bool = True) -> Dict[str, Any]:
        """
        Returns the schema-shaped verdict dict, plus a `skipped` key when QA could not run.
        Never raises for API problems -- an unavailable judge must not look like a FAIL,
        because that would trigger pointless (and billable) regeneration in the retry loop.
        """
        if self.client is None:
            return {"skipped": True, "reason": "no GEMINI_API_KEY", "verdict": None}
        if not os.path.exists(video_path):
            return {"skipped": True, "reason": f"missing video {video_path}", "verdict": None}

        prompt = SIDE_BY_SIDE_PROMPT if side_by_side else SINGLE_VIDEO_PROMPT
        try:
            uploaded = self._upload(video_path)
            response = self.client.models.generate_content(
                model=self.model,
                contents=[uploaded, prompt],
                config={
                    "response_mime_type": "application/json",
                    "response_schema": VERDICT_SCHEMA,
                },
            )
            verdict = json.loads(response.text)
            verdict["skipped"] = False
            verdict["model"] = self.model
            return verdict
        except Exception as e:
            return {"skipped": True, "reason": f"{type(e).__name__}: {e}", "verdict": None}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Perceptual video QA via Gemini.")
    parser.add_argument("--video", required=True)
    parser.add_argument("--single", action="store_true",
                        help="video is the generated clip alone, not a side-by-side")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    args = parser.parse_args()

    result = GeminiJudge(model=args.model).judge(args.video, side_by_side=not args.single)
    print(json.dumps(result, indent=2))


# ---------------------------------------------------------------------------------------
# MARKETING-GRADE SCORING
#
# The judge above answers "is this broken". This one answers "is this good", which is a
# different question and the one nothing in this repo could measure. Every number recorded so
# far -- edge recall, depth correlation, run variance -- scores whether walls land where the
# drawing says. Adherence went from 0.24 to 0.90 while the reference render was deliberately
# kept flat for legibility, and a model steered by a flat evenly-lit reference returns a flat
# evenly-lit photograph. Optimising one axis with nothing watching the other is exactly how you
# arrive at a clip that is geometrically excellent and commercially useless.
#
# Scores are ABSOLUTE against a written rubric rather than free-floating, because an
# unanchored 0-10 drifts between calls and cannot be compared across experiments run days
# apart. The rubric pins 0, 5 and 10 so the same clip scores about the same tomorrow.
# ---------------------------------------------------------------------------------------

QUALITY_RUBRIC = """You are grading a short vertical video of a residential interior, intended
for a property agency's social media feed. Grade it as a demanding creative director would.

Use this scale for every score. Be strict: 7 means genuinely publishable.
  0  unusable - obvious AI artefacts, melted geometry, nothing reads as a real place
  3  a recognisable room, but flat, dead or visibly synthetic
  5  competent amateur - looks like a phone snap of an empty flat
  7  publishable - a viewer scrolling would not question that it is real footage
  10 outstanding - the standard of a high-end architectural photographer

Score these separately. Do not let one influence another.

photorealism      Could a still from this pass as a photograph? Judge materials, surface
                  texture, edges and how light falls on things.
lighting          Is the light directional and believable, with real shadows and depth?
                  Flat, evenly-lit, shadowless renders score low however clean they are.
composition       Does the framing show the space well? Is there depth and a sense of
                  somewhere worth being?
motion_quality    Does the camera move like a real camera - steady, purposeful, well paced?
                  Penalise drifting, sliding, arbitrary speed changes and aimless movement.
temporal_stability Do surfaces and objects stay themselves from frame to frame? Penalise
                  texture swimming, morphing, furniture appearing or vanishing.
marketing_grade   Would a property agency actually publish this to sell a flat?

Also report the single worst defect, and the ONE change most likely to raise the score.
Judge only what you can see. Do not speculate about how it was made."""

QUALITY_SCHEMA = {
    "type": "object",
    "properties": {
        "photorealism": {"type": "integer"},
        "lighting": {"type": "integer"},
        "composition": {"type": "integer"},
        "motion_quality": {"type": "integer"},
        "temporal_stability": {"type": "integer"},
        "marketing_grade": {"type": "integer"},
        "worst_defect": {"type": "string"},
        "single_biggest_fix": {"type": "string"},
        "reads_as_real_footage": {"type": "boolean"},
    },
    "required": ["photorealism", "lighting", "composition", "motion_quality",
                 "temporal_stability", "marketing_grade", "worst_defect",
                 "single_biggest_fix", "reads_as_real_footage"],
}

# The axes that make up the headline number, and what each is worth. Weighted rather than a
# plain mean because for a social feed the thing that stops a scroll is how it LOOKS; motion
# matters mainly when it is wrong. marketing_grade is excluded from the mean deliberately --
# it is the judge's own holistic call and is kept separate so it can be used to sanity-check
# the weighted score rather than being folded into it.
QUALITY_WEIGHTS = {"photorealism": 0.30, "lighting": 0.25, "composition": 0.15,
                   "motion_quality": 0.18, "temporal_stability": 0.12}


def _weighted(scores: Dict[str, Any]) -> float:
    return round(sum(scores[k] * w for k, w in QUALITY_WEIGHTS.items()), 2)


class QualityJudge(GeminiJudge):
    """Scores how GOOD a clip looks, as the second axis alongside geometric adherence."""

    def score(self, video_path: str, repeats: int = 1) -> Dict[str, Any]:
        """
        `repeats` re-asks and averages. Worth using: this pipeline already learned the hard way
        that a single sample can be noise -- an apparent +0.161 from a prompt change evaporated
        to +0.014 across four fresh runs. A judge is a sampler too.
        """
        if self.client is None:
            return {"skipped": True, "reason": "no GEMINI_API_KEY"}
        if not os.path.exists(video_path):
            return {"skipped": True, "reason": f"missing {video_path}"}

        runs = []
        try:
            uploaded = self._upload(video_path)
            for _ in range(max(1, repeats)):
                response = self.client.models.generate_content(
                    model=self.model,
                    contents=[uploaded, QUALITY_RUBRIC],
                    config={"response_mime_type": "application/json",
                            "response_schema": QUALITY_SCHEMA},
                )
                runs.append(json.loads(response.text))
        except Exception as e:
            return {"skipped": True, "reason": f"{type(e).__name__}: {e}"}

        if not runs:
            return {"skipped": True, "reason": "no responses"}

        out = {k: round(sum(r[k] for r in runs) / len(runs), 2) for k in QUALITY_WEIGHTS}
        out["marketing_grade"] = round(sum(r["marketing_grade"] for r in runs) / len(runs), 2)
        out["quality"] = _weighted(out)
        out["reads_as_real_footage"] = sum(r["reads_as_real_footage"] for r in runs) > len(runs) / 2
        out["worst_defect"] = runs[0]["worst_defect"]
        out["single_biggest_fix"] = runs[0]["single_biggest_fix"]
        out["samples"] = len(runs)
        out["model"] = self.model
        out["skipped"] = False
        return out
